services:
  api:
    image: diar-4fis/api

    build:
      context: api
      dockerfile: ./api/Dockerfile

    depends_on:
      - mysql
      - dragonfly

    environment:
      - ENV=production
      - API_PORT=40080
      - API_DOMAIN=diar.4fis.cz
      - API_ALLOWED_ORIGINS=https://diar.4fis.cz
      - API_SESSION_SECRET=${API_SESSION_SECRET}
      - API_FILE_DESTINATION=/usr/src/app/uploads
      - MYSQL_URI=${MYSQL_URI}
      - DRAGONFLY_URI=${DRAGONFLY_URI}
      - DRAGONFLY_PASSWORD=${DRAGONFLY_PASSWORD}
      - CLIENT_URI=https://diar.4fis.cz

    networks:
      - api-network
      - mysql-network
      - dragonfly-network

    # ports:
    #   - 40080:40080

    labels:
      - traefik.enable=true
      - traefik.http.routers.diar-4fis.rule=Host(`diar.4fis.cz`) && PathPrefix(`/api`)
      - traefik.http.routers.diar-4fis.entrypoints=websecure
      - traefik.http.routers.diar-4fis.tls=true
      - traefik.http.routers.diar-4fis.tls.certresolver=letsencrypt
      - traefik.http.services.diar-4fis.loadbalancer.server.port=40080

      - traefik.http.routers.diar-4fis.middlewares=diar-4fis-stripprefix,diar-4fis-redirect-www
      - traefik.http.middlewares.diar-4fis-stripprefix.stripprefix.prefixes=/api
      - traefik.http.middlewares.diar-4fis-redirect-www.redirectregex.regex=^https://www\.(.*)
      - traefik.http.middlewares.diar-4fis-redirect-www.redirectregex.replacement=https://$${1}

    deploy:
      mode: global

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: stop-first

      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: stop-first

      resources:
        limits:
          cpus: 1
          memory: 2048M

    restart: unless-stopped

  # ================================================================ #

  mysql:
    image: mysql

    shm_size: 512mb

    volumes:
      - mysql-data-volume:/var/lib/mysql/data
      - ./scripts/pgsql_create_database.prod.sql:/docker-entrypoint-initdb.d/init.sql

    environment:
      - MYSQL_USER=yASwggdbDvK6F4Wv8lcISVRXqn4hLHJV
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=diar_4fis

    networks:
      - mysql-network

    # ports:
    #   - 3306:3306

    deploy:
      mode: global

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: stop-first

      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: stop-first

      resources:
        limits:
          cpus: 1
          memory: 2048M

    restart: unless-stopped

  # ================================================================ #

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly

    environment:
      - requirepass=${DRAGONFLY_PASSWORD}

    networks:
      - dragonfly-network

    # ports:
    #   - 6379:6379

    deploy:
      mode: global

      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: stop-first

      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: stop-first

      resources:
        limits:
          cpus: 1
          memory: 2048M

    restart: unless-stopped
