networks:
  api-network:
    name: api-network
    external: true
    driver: bridge


  frontend-network:
    name: frontend-network
    external: true
    driver: bridge


  mysql-network:
    name: mysql-network
    external: true
    driver: bridge


  dragonfly-network:
    name: dragonfly-network
    external: true
    driver: bridge
