# ==============================================================================
# Volumes Configuration: Traefik
# Description: Persistent volume definitions for Traefik reverse proxy.
# ==============================================================================

volumes:
  traefik-certificates-volume:
    name: traefik-certificates-volume

  traefik-logs-volume:
    name: traefik-logs-volume
